doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:AUTH_DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
            auth:
                url: '%env(resolve:AUTH_DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
            company:
                url: '%env(resolve:COMPANY_DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
    orm:
        default_entity_manager: auth
        entity_managers:
            auth:
                connection: auth
#                auto_generate_proxy_classes: true
#                enable_lazy_ghost_objects: true
#                report_fields_where_declared: true
#                validate_xml_mapping: true
#                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#                identity_generation_preferences:
#                    Doctrine\DBAL\Platforms\MySQL80Platform: identity
#                auto_mapping: true
#                controller_resolver:
#                    auto_mapping: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                    Auth:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Auth'
                        prefix: 'App\Entity\Auth'
                        alias: Auth
            company:
                connection: company
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
#                auto_generate_proxy_classes: true
#                enable_lazy_ghost_objects: true
#                report_fields_where_declared: true
#                validate_xml_mapping: true
#                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#                identity_generation_preferences:
#                    Doctrine\DBAL\Platforms\MySQL80Platform: identity
#                auto_mapping: true
#                controller_resolver:
#                    auto_mapping: false
                mappings:
                    Company:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Company'
                        prefix: 'App\Entity\Company'
                        alias: Company

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
