when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        # Whether to auto-refresh proxies by default (https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#auto-refresh)
        #database_resetter:
        auto_refresh_proxies: true
        #reset_mode: schema
        #database_resetter:
        orm:
            reset:
                connections:
                    - auth
                    - company
                entity_managers:
                    - auth
                    - company
when@test: *dev
