
services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: mysql_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: VeGV3DWksG
      MYSQL_DATABASE: time_tracker
      MYSQL_USER: time_tracker
      MYSQL_PASSWORD: Kr4ilza4U2
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
