
services:
###> doctrine/doctrine-bundle ###
  database:
#    image: postgres:${POSTGRES_VERSION:-15}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-time_tracker_auth}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Kr4ilza4U2}
#      POSTGRES_USER: ${POSTGRES_USER:-time_tracker}
#      ports:
#        - 5432:5432
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
    container_name: mysql_database
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: VeGV3DWksG
      MYSQL_DATABASE: time_tracker
      MYSQL_USER: time_tracker
      MYSQL_PASSWORD: Kr4ilza4U2
    ports:
      - '4306:3306'
    volumes:
      - mysql:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  mysql:
###< doctrine/doctrine-bundle ###
